import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '95%',
    height: 'auto',
    flex: 1,
    alignItems: 'center',
    margin: 12,
    padding: 12,
    borderRadius: 12,
    paddingBottom: 2,
    backgroundColor: 'white',
    gap: 12,
  },
  icon: {
    flex: 1,
    width: 150,
    maxHeight: 150,
    borderWidth: 8,
    borderRadius: 100,
    borderColor: '#1f1d1d',
    padding: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userInfo: {
    color: 'black',
    textAlign: 'center',
    fontSize: 28,
    fontWeight: '500',
  },
  userHandle: {
    color: 'darkgray',
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '500',
  },
  userSettings: {
    width: '100%',
    height: 'auto',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 6,
    marginBottom: 0,
    marginLeft: 1,
    marginRight: 1,
    padding: 14,
    borderRadius: 26,
    borderBottomEndRadius: 0,
    borderBottomStartRadius: 0,
    borderWidth: 2,
    borderColor: '#1f1d1d',
    backgroundColor: '#1f1d1d',
    gap: 22,
  },
  userSettingsButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '80%',
    maxHeight: '15%',
    backgroundColor: '#1f1d1d',
    borderColor: 'white',
    borderWidth: 1,
    borderRadius: 100,
  },
  userSettingsButtonText: {
    fontWeight: '500',
    fontSize: 24,
    color: 'white',
  },
});
